spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-social-network
    username: postgres
    password: tiendat1409
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: datien
    password: tiendat1
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: zcDTIEdI/g7pT8joK9eZS57JdbF+wPikUpCgUAdOfdwdvcYbWe9RWW7ciYnrANIw
      expiration: 864000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088